### ISSUE TITLE
Is there a way to use sub-projects that are externally compiled?

### ISSUE THREAD

**Issue by cuchaz** [jerkar/jerkar#61]
I've been using Jerkar in multi-project builds lately where dependent projects are already compiled by another non-Jerkar process. Ideally, I'd like the Eclipse `.classpath` (via `eclipse#generateFiles`) to use project references (for the nice IDE integration), but I don't want to teach Jerkar how to compile these sub-projects.

My first approach was to try something like this:
```java
@JkProject("/path/to/externalProject")
JkJavaBuild externalProject;

@Override
public JkDependencies dependencies() {
	return JkDependencies.builder()			
		.on(externalProject.asJavaDependency())
		.build();
}
```

This has the correct `.classpath` in Eclipse, but when trying to compile the project in Jerkar, Jerkar wants to compile `externalProject` and fails because it doesn't know how. The type of compilation failure is unimportant here, because the desired behavior is for Jerkar to not attempt compilation at all. But instead, refer to a folder of already-compiled classes for that dependency.

My second attempt to do this was like this:
```java
@Override
public JkDependencies dependencies() {
	return JkDependencies.builder()
		.on(new File("/path/to/externalProject/bin"))
		.build();
}
```

This approach has the correct Jerkar compilation behavior for the project, but the Eclipse `.classpath` uses class folder references instead of project references, which results in worse IDE integration.

Is there a way to have both? The Eclipse `.classpath` project references and the pre-compiled class folder for the same dependency?

If this doesn't exist in Jerkar yet, I'd be happy to write a PR if you would point me in the right direction.

**Comment by djeang** [comment]
For me 
```
@Override
public JkDependencies dependencies() {
	return JkDependencies.builder()
		.on(new File("/path/to/externalProject/bin"))
		.build();
}
```
is correct. 

If Jerkar is not involved at all in dependee project build, you don't need to hold a JkJavaBuild reference on it.

So far I found ok to have just the folder reference in .classpath (and not the project dependency) but
I understand that it makes beter integration. So i would be please you provide PR.

To make it possible Jerkar should detect that bin folder is part of an Eclipse project (maybe checking the presence of the .classpath and .project file, and that the dependedency bin file is the output folder of that project). In that case, Jerkar should add a classpathentry typed 'src' instead of 'lib'.

The class to adapt is `DotClasspathGenerator`.  I think method already exist to generate classpathentry typed 'src'.

**Comment by cuchaz** [comment]
Ok, thanks. I'll look into it.
